name: Update README

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "code/**"
      - "review/**"
      - "scripts/**"
  schedule:
    - cron: "15 0 * * *"  # UTC 00:15 = KST 09:15

permissions:
  contents: write

concurrency:
  group: update-readme
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug tree
        run: |
          echo "::group::root"; ls -al; echo "::endgroup::"
          echo "::group::scripts"; ls -al scripts || true; echo "::endgroup::"

      - name: Install deps (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Prepare template (fallback copy to root)
        run: |
          if [ -f scripts/README.template.md ] && [ ! -f README.template.md ]; then
            cp scripts/README.template.md README.template.md
          fi

      - name: Generate README
        run: python scripts/analyze.py

      - name: Commit & Push if changed
        run: |
          if ! git diff --quiet README.md; then
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git add README.md
            git commit -m "chore: auto-update dashboard [skip ci]"
            git push
          else
            echo "No README changes."
          fi
